#ifndef __ASSET_TYPES_HPP__
#define __ASSET_TYPES_HPP__

#include "Templates.hpp"

namespace BloodSword::Asset
{
    // asset type
    enum class Type
    {
        NONE = -1,
        WARRIOR,
        TRICKSTER,
        SAGE,
        ENCHANTER,
        GENERIC,
        PERSON,
        ASSASSIN,
        BARBARIAN,
        DIRGE_MAN,
        SKIAPYR,
        MAGUS_VYL,
        ICON_THE_UNGODLY,
        MAN_IN_BLUE,
        CORPSE,
        BOWMAN,
        DIRGE,
        ECHIDNA,
        SKRYMIR_THE_GIANT,
        GUARD,
        ADVENTURER,
        RANGER,
        SMEABORG,
        GIANT_SPIDER,
        ICON_THE_WARLOCK,
        NIGHT_ELF,
        QUEL,
        DEATH_FETISHIST,
        NEBULARON,
        YOUNG_SORCERESS,
        EIDOLON,
        GARGOYLE,
        UP,
        DOWN,
        LEFT,
        RIGHT,
        WALL,
        IMPASSABLE,
        EMPTY_SPACE,
        WHITE_SPACE,
        VERTICAL_SURFACE,
        WINDOW,
        DOOR,
        DOORWAY,
        LEDGE,
        ROCKS,
        CHASM,
        BRIDGE,
        TOWER,
        MOVE,
        FIGHT,
        SHOOT,
        SHURIKEN,
        DEFEND,
        FLEE,
        CALL_TO_MIND,
        CAST_SPELL,
        DODGING,
        ARCHERY,
        QUARTERSTAFF,
        HEALING,
        ESP,
        PARANORMAL_SIGHT,
        EXORCISM,
        LEVITATION,
        SPELLS,
        ITEMS,
        EXIT,
        CONFIRM,
        CANCEL,
        BACK,
        VOLCANO_SPRAY,
        NIGHTHOWL,
        WHITE_FIRE,
        SWORDTHRUST,
        EYE_OF_THE_TIGER,
        IMMEDIATE_DELIVERANCE,
        MISTS_OF_DEATH,
        THE_VAMPIRE_SPELL,
        PILLAR_OF_SALT,
        SHEET_LIGHTNING,
        GHASTLY_TOUCH,
        NEMESIS_BOLT,
        SERVILE_ENTHRALMENT,
        SUMMON_FALTYN,
        PREDICTION,
        DETECT_ENCHANTMENT,
        IGNORE_ARMOUR,
        ENTHRALMENT_IMMUNITY,
        DICE1,
        DICE2,
        DICE3,
        DICE4,
        DICE5,
        DICE6,
        AWARENESS,
        PSYCHIC_ABILITY,
        ENDURANCE,
        DAMAGE,
        ARMOUR,
        UNARMED_COMBAT,
        HEAL,
        WOODEN_DOOR,
        CENTER,
        CHESSBOARD,
        STAIRS,
        DUNGEON_EXIT,
        GATE,
        SELECT,
        POISONED_DAGGER,
        CARD_BLANK,
        CARD_JOKER,
        ACE_CLUBS,
        ACE_DIAMONDS,
        ACE_HEARTS,
        ACE_SPADES,
        KING_CLUBS,
        KING_DIAMONDS,
        KING_HEARTS,
        KING_SPADES,
        GAME,
        USE,
        TRADE,
        MONEY,
        DROP,
        INVENTORY,
        INFO,
        IDENTIFY,
        DRINK,
        READ,
        DICE_GAME,
        KALUGEN,
        FOOD,
        BATTLE_ORDER,
        LOAD,
        SAVE,
        MUMMY_HEAD,
        ROCK,
        QUIVER,
        CENSER,
        STEEL_SCEPTRE,
        BEORN,
        KNIGHT,
        NEMESIS,
        WATERFALL,
        ROPE_BRIDGE,
        ROPE_BRIDGE_INVERTED,
        WAVES,
        WAVE_CREST,
        GEAR,
        DAGGER_OF_VISLET,
        GONDOLIER,
        WOODEN_PLANK,
        WATER,
        RUSTY_WEAPON,
        BROKEN_WEAPON,
        GOLDEN_SNUFF_BOX,
        DRAGONLORD_GEM,
        FANGS,
        HAG,
        PILLAR,
        BROKEN_PILLARS,
        FIRE_SHIELD,
        TROPHY
    };

    template <typename T>
    using AssetMapping = BloodSword::UnorderedMap<Asset::Type, T>;

    typedef std::vector<Asset::Type> List;

    BloodSword::Mapping<Asset::Type> TypeMapping = {
        {Asset::Type::NONE, "NONE"},
        {Asset::Type::WARRIOR, "WARRIOR"},
        {Asset::Type::TRICKSTER, "TRICKSTER"},
        {Asset::Type::SAGE, "SAGE"},
        {Asset::Type::ENCHANTER, "ENCHANTER"},
        {Asset::Type::GENERIC, "GENERIC"},
        {Asset::Type::ASSASSIN, "ASSASSIN"},
        {Asset::Type::BARBARIAN, "BARBARIAN"},
        {Asset::Type::DIRGE_MAN, "DIRGE MAN"},
        {Asset::Type::SKIAPYR, "SKIAPYR"},
        {Asset::Type::MAGUS_VYL, "MAGUS VYL"},
        {Asset::Type::ICON_THE_UNGODLY, "ICON THE UNGODLY"},
        {Asset::Type::MAN_IN_BLUE, "MAN IN BLUE"},
        {Asset::Type::CORPSE, "CORPSE"},
        {Asset::Type::BOWMAN, "BOWMAN"},
        {Asset::Type::DIRGE, "DIRGE"},
        {Asset::Type::ECHIDNA, "ECHIDNA"},
        {Asset::Type::SKRYMIR_THE_GIANT, "SKRYMIR THE GIANT"},
        {Asset::Type::GUARD, "GUARD"},
        {Asset::Type::ADVENTURER, "ADVENTURER"},
        {Asset::Type::RANGER, "RANGER"},
        {Asset::Type::SMEABORG, "SMEABORG"},
        {Asset::Type::GIANT_SPIDER, "GIANT SPIDER"},
        {Asset::Type::ICON_THE_WARLOCK, "ICON THE WARLOCK"},
        {Asset::Type::NIGHT_ELF, "NIGHT ELF"},
        {Asset::Type::QUEL, "QUEL"},
        {Asset::Type::DEATH_FETISHIST, "DEATH FETISHIST"},
        {Asset::Type::NEBULARON, "NEBULARON"},
        {Asset::Type::EIDOLON, "EIDOLON"},
        {Asset::Type::GARGOYLE, "GARGOYLE"},
        {Asset::Type::UP, "UP"},
        {Asset::Type::DOWN, "DOWN"},
        {Asset::Type::LEFT, "LEFT"},
        {Asset::Type::RIGHT, "RIGHT"},
        {Asset::Type::WALL, "WALL"},
        {Asset::Type::IMPASSABLE, "IMPASSABLE"},
        {Asset::Type::EMPTY_SPACE, "EMPTY SPACE"},
        {Asset::Type::WHITE_SPACE, "WHITE SPACE"},
        {Asset::Type::VERTICAL_SURFACE, "VERTICAL SURFACE"},
        {Asset::Type::WINDOW, "WINDOW"},
        {Asset::Type::DOOR, "DOOR"},
        {Asset::Type::DOORWAY, "DOORWAY"},
        {Asset::Type::LEDGE, "LEDGE"},
        {Asset::Type::ROCKS, "ROCKS"},
        {Asset::Type::CHASM, "CHASM"},
        {Asset::Type::BRIDGE, "BRIDGE"},
        {Asset::Type::TOWER, "TOWER"},
        {Asset::Type::MOVE, "MOVE"},
        {Asset::Type::FIGHT, "FIGHT"},
        {Asset::Type::SHOOT, "SHOOT"},
        {Asset::Type::SHURIKEN, "SHURIKEN"},
        {Asset::Type::DEFEND, "DEFEND"},
        {Asset::Type::FLEE, "FLEE"},
        {Asset::Type::CALL_TO_MIND, "CALL TO MIND"},
        {Asset::Type::CAST_SPELL, "CAST SPELL"},
        {Asset::Type::DODGING, "DODGING"},
        {Asset::Type::ARCHERY, "ARCHERY"},
        {Asset::Type::QUARTERSTAFF, "QUARTERSTAFF"},
        {Asset::Type::HEALING, "HEALING"},
        {Asset::Type::ESP, "ESP"},
        {Asset::Type::PARANORMAL_SIGHT, "PARANORMAL SIGHT"},
        {Asset::Type::EXORCISM, "EXORCISM"},
        {Asset::Type::LEVITATION, "LEVITATION"},
        {Asset::Type::SPELLS, "SPELLS"},
        {Asset::Type::ITEMS, "ITEMS"},
        {Asset::Type::EXIT, "EXIT"},
        {Asset::Type::CONFIRM, "CONFIRM"},
        {Asset::Type::CANCEL, "CANCEL"},
        {Asset::Type::BACK, "BACK"},
        {Asset::Type::VOLCANO_SPRAY, "VOLCANO SPRAY"},
        {Asset::Type::NIGHTHOWL, "NIGHTHOWL"},
        {Asset::Type::WHITE_FIRE, "WHITE FIRE"},
        {Asset::Type::SWORDTHRUST, "SWORDTHRUST"},
        {Asset::Type::EYE_OF_THE_TIGER, "EYE OF THE TIGER"},
        {Asset::Type::IMMEDIATE_DELIVERANCE, "IMMEDIATE DELIVERANCE"},
        {Asset::Type::MISTS_OF_DEATH, "MISTS OF DEATH"},
        {Asset::Type::THE_VAMPIRE_SPELL, "THE VAMPIRE SPELL"},
        {Asset::Type::PILLAR_OF_SALT, "PILLAR OF SALT"},
        {Asset::Type::SHEET_LIGHTNING, "SHEET LIGHTNING"},
        {Asset::Type::GHASTLY_TOUCH, "GHASTLY TOUCH"},
        {Asset::Type::NEMESIS_BOLT, "NEMESIS BOLT"},
        {Asset::Type::SERVILE_ENTHRALMENT, "SERVILE ENTHRALMENT"},
        {Asset::Type::SUMMON_FALTYN, "SUMMON FALTYN"},
        {Asset::Type::PREDICTION, "PREDICTION"},
        {Asset::Type::DETECT_ENCHANTMENT, "DETECT ENCHANTMENT"},
        {Asset::Type::DICE1, "DICE1"},
        {Asset::Type::DICE2, "DICE2"},
        {Asset::Type::DICE3, "DICE3"},
        {Asset::Type::DICE4, "DICE4"},
        {Asset::Type::DICE5, "DICE5"},
        {Asset::Type::DICE6, "DICE6"},
        {Asset::Type::IGNORE_ARMOUR, "IGNORE ARMOUR"},
        {Asset::Type::AWARENESS, "AWARENESS"},
        {Asset::Type::PSYCHIC_ABILITY, "PSYCHIC ABILITY"},
        {Asset::Type::ENDURANCE, "ENDURANCE"},
        {Asset::Type::DAMAGE, "DAMAGE"},
        {Asset::Type::ARMOUR, "ARMOUR"},
        {Asset::Type::UNARMED_COMBAT, "UNARMED COMBAT"},
        {Asset::Type::HEAL, "HEAL"},
        {Asset::Type::WOODEN_DOOR, "WOODEN DOOR"},
        {Asset::Type::CENTER, "CENTER"},
        {Asset::Type::CHESSBOARD, "CHESSBOARD"},
        {Asset::Type::STAIRS, "STAIRS"},
        {Asset::Type::DUNGEON_EXIT, "DUNGEON EXIT"},
        {Asset::Type::GATE, "GATE"},
        {Asset::Type::SELECT, "SELECT"},
        {Asset::Type::POISONED_DAGGER, "POISONED DAGGER"},
        {Asset::Type::CARD_BLANK, "CARD BLANK"},
        {Asset::Type::CARD_JOKER, "CARD JOKER"},
        {Asset::Type::ACE_CLUBS, "ACE CLUBS"},
        {Asset::Type::ACE_DIAMONDS, "ACE DIAMONDS"},
        {Asset::Type::ACE_HEARTS, "ACE HEARTS"},
        {Asset::Type::ACE_SPADES, "ACE SPADES"},
        {Asset::Type::KING_CLUBS, "KING CLUBS"},
        {Asset::Type::KING_DIAMONDS, "KING DIAMONDS"},
        {Asset::Type::KING_HEARTS, "KING HEARTS"},
        {Asset::Type::KING_SPADES, "KING SPADES"},
        {Asset::Type::GAME, "GAME"},
        {Asset::Type::USE, "USE"},
        {Asset::Type::TRADE, "TRADE"},
        {Asset::Type::MONEY, "MONEY"},
        {Asset::Type::DROP, "DROP"},
        {Asset::Type::INVENTORY, "INVENTORY"},
        {Asset::Type::INFO, "INFO"},
        {Asset::Type::IDENTIFY, "IDENTIFY"},
        {Asset::Type::DRINK, "DRINK"},
        {Asset::Type::READ, "READ"},
        {Asset::Type::DICE_GAME, "DICE GAME"},
        {Asset::Type::KALUGEN, "KALUGEN"},
        {Asset::Type::FOOD, "FOOD"},
        {Asset::Type::BATTLE_ORDER, "BATTLE ORDER"},
        {Asset::Type::LOAD, "LOAD"},
        {Asset::Type::SAVE, "SAVE"},
        {Asset::Type::MUMMY_HEAD, "MUMMY HEAD"},
        {Asset::Type::ROCK, "ROCK"},
        {Asset::Type::QUIVER, "QUIVER"},
        {Asset::Type::CENSER, "CENSER"},
        {Asset::Type::STEEL_SCEPTRE, "STEEL SCEPTRE"},
        {Asset::Type::BEORN, "BEORN"},
        {Asset::Type::KNIGHT, "KNIGHT"},
        {Asset::Type::NEMESIS, "NEMESIS"},
        {Asset::Type::PERSON, "PERSON"},
        {Asset::Type::WATERFALL, "WATERFALL"},
        {Asset::Type::ROPE_BRIDGE, "ROPE BRIDGE"},
        {Asset::Type::ROPE_BRIDGE_INVERTED, "ROPE BRIDGE INVERTED"},
        {Asset::Type::WAVES, "WAVES"},
        {Asset::Type::WAVE_CREST, "WAVE CREST"},
        {Asset::Type::GEAR, "GEAR"},
        {Asset::Type::DAGGER_OF_VISLET, "DAGGER OF VISLET"},
        {Asset::Type::GONDOLIER, "GONDOLIER"},
        {Asset::Type::WOODEN_PLANK, "WOODEN PLANK"},
        {Asset::Type::WATER, "WATER"},
        {Asset::Type::RUSTY_WEAPON, "RUSTY WEAPON"},
        {Asset::Type::BROKEN_WEAPON, "BROKEN WEAPON"},
        {Asset::Type::GOLDEN_SNUFF_BOX, "GOLDEN SNUFF-BOX"},
        {Asset::Type::DRAGONLORD_GEM, "DRAGONLORD GEM"},
        {Asset::Type::FANGS, "FANGS"},
        {Asset::Type::HAG, "HAG"},
        {Asset::Type::PILLAR, "PILLAR"},
        {Asset::Type::BROKEN_PILLARS, "BROKEN PILLARS"},
        {Asset::Type::FIRE_SHIELD, "FIRE SHIELD"},
        {Asset::Type::TROPHY, "TROPHY"}};

    Asset::Type Map(const char *asset)
    {
        return BloodSword::Find(Asset::TypeMapping, asset);
    }

    Asset::Type Map(std::string asset)
    {
        return Asset::Map(asset.c_str());
    }
}

#endif
