#ifndef __ASSET_TYPES_HPP__
#define __ASSET_TYPES_HPP__

#include <string>

#include "Templates.hpp"

namespace BloodSword::Asset
{
    // asset type
    enum class Type
    {
        NONE = -1,
        WARRIOR,
        TRICKSTER,
        SAGE,
        ENCHANTER,
        ASSASSIN,
        BARBARIAN,
        DIRGE_MAN,
        SKIAPYR,
        MAGUS_VYL,
        ICON_THE_UNGODLY,
        MAN_IN_BLUE,
        CORPSE,
        BOWMAN,
        DIRGE,
        ECHIDNA,
        SKRYMIR_THE_GIANT,
        GUARD,
        ADVENTURER,
        RANGER,
        SMEABORG,
        GIANT_SPIDER,
        ICON_THE_WARLOCK,
        NIGHT_ELF,
        QUEL,
        DEATH_FETISHIST,
        NEBULARON,
        YOUNG_SORCERESS,
        EIDOLON,
        GARGOYLE,
        UP,
        DOWN,
        LEFT,
        RIGHT,
        WALL,
        IMPASSABLE,
        EMPTY_SPACE,
        WHITE_SPACE,
        VERTICAL_SURFACE,
        WINDOW,
        DOOR,
        LEDGE,
        ROCKS,
        CHASM,
        BRIDGE,
        TOWER,
        MOVE,
        FIGHT,
        SHOOT,
        SHURIKEN,
        DEFEND,
        FLEE,
        CALL_TO_MIND,
        CAST_SPELL,
        DODGING,
        ARCHERY,
        QUARTERSTAFF,
        HEALING,
        ESP,
        PARANORMAL_SIGHT,
        EXORCISM,
        LEVITATION,
        SPELLS,
        ITEMS,
        EXIT,
        CONFIRM,
        CANCEL,
        BACK,
        VOLCANO_SPRAY,
        NIGHTHOWL,
        WHITE_FIRE,
        SWORDTHRUST,
        EYE_OF_THE_TIGER,
        IMMEDIATE_DELIVERANCE,
        MISTS_OF_DEATH,
        THE_VAMPIRE_SPELL,
        PILLAR_OF_SALT,
        SHEET_LIGHTNING,
        GHASTLY_TOUCH,
        NEMESIS_BOLT,
        SERVILE_ENTHRALMENT,
        SUMMON_FALTYN,
        PREDICTION,
        DETECT_ENCHANTMENT,
        IGNORE_ARMOUR,
        ENTHRALMENT_IMMUNITY,
        DICE1,
        DICE2,
        DICE3,
        DICE4,
        DICE5,
        DICE6,
        AWARENESS,
        PSYCHIC_ABILITY,
        ENDURANCE,
        DAMAGE,
        ARMOUR,
        UNARMED_COMBAT,
        HEAL,
        WOODEN_DOOR,
        CENTER,
        CHESSBOARD,
        STAIRS,
        DUNGEON_EXIT,
        GATE,
        SELECT,
        POISONED_DAGGER
    };

    template <typename T>
    using AssetMapping = BloodSword::UnorderedMap<Asset::Type, T>;

    BloodSword::Mapping<Asset::Type> TypeMapping = {
        {Asset::Type::NONE, "NONE"},
        {Asset::Type::WARRIOR, "WARRIOR"},
        {Asset::Type::TRICKSTER, "TRICKSTER"},
        {Asset::Type::SAGE, "SAGE"},
        {Asset::Type::ENCHANTER, "ENCHANTER"},
        {Asset::Type::ASSASSIN, "ASSASSIN"},
        {Asset::Type::BARBARIAN, "BARBARIAN"},
        {Asset::Type::DIRGE_MAN, "DIRGE MAN"},
        {Asset::Type::SKIAPYR, "SKIAPYR"},
        {Asset::Type::MAGUS_VYL, "MAGUS VYL"},
        {Asset::Type::ICON_THE_UNGODLY, "ICON THE UNGODLY"},
        {Asset::Type::MAN_IN_BLUE, "MAN IN BLUE"},
        {Asset::Type::CORPSE, "CORPSE"},
        {Asset::Type::BOWMAN, "BOWMAN"},
        {Asset::Type::DIRGE, "DIRGE"},
        {Asset::Type::ECHIDNA, "ECHIDNA"},
        {Asset::Type::SKRYMIR_THE_GIANT, "SKRYMIR THE GIANT"},
        {Asset::Type::GUARD, "GUARD"},
        {Asset::Type::ADVENTURER, "ADVENTURER"},
        {Asset::Type::RANGER, "RANGER"},
        {Asset::Type::SMEABORG, "SMEABORG"},
        {Asset::Type::GIANT_SPIDER, "GIANT SPIDER"},
        {Asset::Type::ICON_THE_WARLOCK, "ICON THE WARLOCK"},
        {Asset::Type::NIGHT_ELF, "NIGHT ELF"},
        {Asset::Type::QUEL, "QUEL"},
        {Asset::Type::DEATH_FETISHIST, "DEATH FETISHIST"},
        {Asset::Type::NEBULARON, "NEBULARON"},
        {Asset::Type::EIDOLON, "EIDOLON"},
        {Asset::Type::GARGOYLE, "GARGOYLE"},
        {Asset::Type::UP, "UP"},
        {Asset::Type::DOWN, "DOWN"},
        {Asset::Type::LEFT, "LEFT"},
        {Asset::Type::RIGHT, "RIGHT"},
        {Asset::Type::WALL, "WALL"},
        {Asset::Type::IMPASSABLE, "IMPASSABLE"},
        {Asset::Type::EMPTY_SPACE, "EMPTY SPACE"},
        {Asset::Type::WHITE_SPACE, "WHITE SPACE"},
        {Asset::Type::VERTICAL_SURFACE, "VERTICAL SURFACE"},
        {Asset::Type::WINDOW, "WINDOW"},
        {Asset::Type::DOOR, "DOOR"},
        {Asset::Type::LEDGE, "LEDGE"},
        {Asset::Type::ROCKS, "ROCKS"},
        {Asset::Type::CHASM, "CHASM"},
        {Asset::Type::BRIDGE, "BRIDGE"},
        {Asset::Type::TOWER, "TOWER"},
        {Asset::Type::MOVE, "MOVE"},
        {Asset::Type::FIGHT, "FIGHT"},
        {Asset::Type::SHOOT, "SHOOT"},
        {Asset::Type::SHURIKEN, "SHURIKEN"},
        {Asset::Type::DEFEND, "DEFEND"},
        {Asset::Type::FLEE, "FLEE"},
        {Asset::Type::CALL_TO_MIND, "CALL TO MIND"},
        {Asset::Type::CAST_SPELL, "CAST SPELL"},
        {Asset::Type::DODGING, "DODGING"},
        {Asset::Type::ARCHERY, "ARCHERY"},
        {Asset::Type::QUARTERSTAFF, "QUARTERSTAFF"},
        {Asset::Type::HEALING, "HEALING"},
        {Asset::Type::ESP, "ESP"},
        {Asset::Type::PARANORMAL_SIGHT, "PARANORMAL SIGHT"},
        {Asset::Type::EXORCISM, "EXORCISM"},
        {Asset::Type::LEVITATION, "LEVITATION"},
        {Asset::Type::SPELLS, "SPELLS"},
        {Asset::Type::ITEMS, "ITEMS"},
        {Asset::Type::EXIT, "EXIT"},
        {Asset::Type::CONFIRM, "CONFIRM"},
        {Asset::Type::CANCEL, "CANCEL"},
        {Asset::Type::BACK, "BACK"},
        {Asset::Type::VOLCANO_SPRAY, "VOLCANO SPRAY"},
        {Asset::Type::NIGHTHOWL, "NIGHTHOWL"},
        {Asset::Type::WHITE_FIRE, "WHITE FIRE"},
        {Asset::Type::SWORDTHRUST, "SWORDTHRUST"},
        {Asset::Type::EYE_OF_THE_TIGER, "EYE OF THE TIGER"},
        {Asset::Type::IMMEDIATE_DELIVERANCE, "IMMEDIATE DELIVERANCE"},
        {Asset::Type::MISTS_OF_DEATH, "MISTS OF DEATH"},
        {Asset::Type::THE_VAMPIRE_SPELL, "THE VAMPIRE SPELL"},
        {Asset::Type::PILLAR_OF_SALT, "PILLAR OF SALT"},
        {Asset::Type::SHEET_LIGHTNING, "SHEET LIGHTNING"},
        {Asset::Type::GHASTLY_TOUCH, "GHASTLY TOUCH"},
        {Asset::Type::NEMESIS_BOLT, "NEMESIS BOLT"},
        {Asset::Type::SERVILE_ENTHRALMENT, "SERVILE ENTHRALMENT"},
        {Asset::Type::SUMMON_FALTYN, "SUMMON FALTYN"},
        {Asset::Type::PREDICTION, "PREDICTION"},
        {Asset::Type::DETECT_ENCHANTMENT, "DETECT ENCHANTMENT"},
        {Asset::Type::DICE1, "DICE1"},
        {Asset::Type::DICE2, "DICE2"},
        {Asset::Type::DICE3, "DICE3"},
        {Asset::Type::DICE4, "DICE4"},
        {Asset::Type::DICE5, "DICE5"},
        {Asset::Type::DICE6, "DICE6"},
        {Asset::Type::IGNORE_ARMOUR, "IGNORE ARMOUR"},
        {Asset::Type::AWARENESS, "AWARENESS"},
        {Asset::Type::PSYCHIC_ABILITY, "PSYCHIC ABILITY"},
        {Asset::Type::ENDURANCE, "ENDURANCE"},
        {Asset::Type::DAMAGE, "DAMAGE"},
        {Asset::Type::ARMOUR, "ARMOUR"},
        {Asset::Type::UNARMED_COMBAT, "UNARMED COMBAT"},
        {Asset::Type::HEAL, "HEAL"},
        {Asset::Type::WOODEN_DOOR, "WOODEN DOOR"},
        {Asset::Type::CENTER, "CENTER"},
        {Asset::Type::CHESSBOARD, "CHESSBOARD"},
        {Asset::Type::STAIRS, "STAIRS"},
        {Asset::Type::DUNGEON_EXIT, "DUNGEON EXIT"},
        {Asset::Type::GATE, "GATE"},
        {Asset::Type::SELECT, "SELECT"},
        {Asset::Type::POISONED_DAGGER, "POISONED DAGGER"}};

    Asset::Type Map(const char *asset)
    {
        return BloodSword::Find(Asset::TypeMapping, asset);
    }

    Asset::Type Map(std::string asset)
    {
        return Asset::Map(asset.c_str());
    }
}

#endif
