#ifndef __CONDITION_TYPES_HPP__
#define __CONDITION_TYPES_HPP__

#include "Templates.hpp"

namespace BloodSword::Conditions
{
    enum class Type
    {
        NONE = -1,
        NORMAL,
        IN_PARTY,
        CHOOSE_PLAYER,
        CHOSEN_PLAYER,
        BATTLE_VICTORY,
        BATTLE_FLEE,
        BATTLE_ENTHRALMENT,
        BATTLE_VICTORY_OR_ENTHRALMENT,
        HAS_ITEM,
        HAS_CHARGED_ITEM,
        USE_ITEM,
        DROP_ITEM,
        TAKE_ITEM,
        GET_ITEM,
        REVEAL_ITEM,
        TAKE_ITEMS,
        GAIN_ENDURANCE,
        LOSE_ENDURANCE,
        CHOOSE_NUMBER,
        CHOSEN_NUMBER,
        PARTY_WOUNDED,
        PREVIOUS_LOCATION,
        TEST_ATTRIBUTE,
        LOSE_ALL,
        HAVE_COLLEAGUES,
        SOLO,
        GAIN_STATUS,
        LOSE_STATUS,
        FIRST,
        LAST,
        TEST_GAIN_STATUS,
        COUNT_STATUS,
        SELECT_MULTIPLE,
        CALL_TO_MIND,
        FORGET_SPELL,
        KALUGEN_SELECT,
        KALUGEN_SCORE,
        KALUGEN_LIST,
        KALUGEN_PLAY,
        DISCARD_ITEMS,
        RECEIVE_ITEM,
        IN_PARTY_WITH_ITEM,
        SELECT_PLAYER,
        LOSE_WEAPONS,
        LOSE_ARMOUR,
        ITEM_EFFECT,
        STAKE,
        SET,
        GET,
        NUMBER,
        COPY,
        MATH,
        ROLL,
        IF,
        IF_MATH,
        AND,
        OR,
        ADD_TO_ITEM,
        SHOW_VARIABLES,
        EAT_FOOD,
        SHOW_MESSAGE,
        TEXTBOX,
        COUNT_ITEMS,
        PSYCHIC_SPELL,
        IS_DEAD,
        COLLECT,
        PERMANENT_ATTRIBUTE_GAIN,
        CHARGE,
        DISCHARGE,
        KILL_PLAYER,
        GAIN_ATTRIBUTE,
        DAMAGE_PLAYER,
        FAIL_THEN_DIE,
        SELECT_DICE,
        MULTIPLE_DICE
    };

    BloodSword::Mapping<Conditions::Type> TypeMapping = {
        {Conditions::Type::NONE, "NONE"},
        {Conditions::Type::NORMAL, "NORMAL"},
        {Conditions::Type::IN_PARTY, "IN PARTY"},
        {Conditions::Type::CHOOSE_PLAYER, "CHOOSE PLAYER"},
        {Conditions::Type::CHOSEN_PLAYER, "CHOSEN PLAYER"},
        {Conditions::Type::BATTLE_VICTORY, "BATTLE VICTORY"},
        {Conditions::Type::BATTLE_FLEE, "BATTLE FLEE"},
        {Conditions::Type::BATTLE_ENTHRALMENT, "BATTLE ENTHRALMENT"},
        {Conditions::Type::BATTLE_VICTORY_OR_ENTHRALMENT, "BATTLE VICTORY OR ENTHRALMENT"},
        {Conditions::Type::HAS_ITEM, "HAS ITEM"},
        {Conditions::Type::HAS_CHARGED_ITEM, "HAS CHARGED ITEM"},
        {Conditions::Type::USE_ITEM, "USE ITEM"},
        {Conditions::Type::DROP_ITEM, "DROP ITEM"},
        {Conditions::Type::TAKE_ITEM, "TAKE ITEM"},
        {Conditions::Type::GET_ITEM, "GET ITEM"},
        {Conditions::Type::TAKE_ITEMS, "TAKE ITEMS"},
        {Conditions::Type::GAIN_ENDURANCE, "GAIN ENDURANCE"},
        {Conditions::Type::LOSE_ENDURANCE, "LOSE ENDURANCE"},
        {Conditions::Type::CHOOSE_NUMBER, "CHOOSE NUMBER"},
        {Conditions::Type::CHOSEN_NUMBER, "CHOSEN NUMBER"},
        {Conditions::Type::PARTY_WOUNDED, "PARTY WOUNDED"},
        {Conditions::Type::PREVIOUS_LOCATION, "PREVIOUS LOCATION"},
        {Conditions::Type::TEST_ATTRIBUTE, "TEST ATTRIBUTE"},
        {Conditions::Type::LOSE_ALL, "LOSE ALL"},
        {Conditions::Type::HAVE_COLLEAGUES, "HAVE COLLEAGUES"},
        {Conditions::Type::SOLO, "SOLO"},
        {Conditions::Type::GAIN_STATUS, "GAIN STATUS"},
        {Conditions::Type::FIRST, "FIRST"},
        {Conditions::Type::LAST, "LAST"},
        {Conditions::Type::TEST_GAIN_STATUS, "TEST GAIN STATUS"},
        {Conditions::Type::COUNT_STATUS, "COUNT STATUS"},
        {Conditions::Type::LOSE_STATUS, "LOSE STATUS"},
        {Conditions::Type::SELECT_MULTIPLE, "SELECT MULTIPLE"},
        {Conditions::Type::CALL_TO_MIND, "CALL TO MIND"},
        {Conditions::Type::FORGET_SPELL, "FORGET SPELL"},
        {Conditions::Type::KALUGEN_SELECT, "KALUGEN SELECT"},
        {Conditions::Type::KALUGEN_SCORE, "KALUGEN SCORE"},
        {Conditions::Type::KALUGEN_LIST, "KALUGEN LIST"},
        {Conditions::Type::KALUGEN_PLAY, "KALUGEN PLAY"},
        {Conditions::Type::DISCARD_ITEMS, "DISCARD ITEMS"},
        {Conditions::Type::RECEIVE_ITEM, "RECEIVE ITEM"},
        {Conditions::Type::IN_PARTY_WITH_ITEM, "IN PARTY WITH ITEM"},
        {Conditions::Type::SELECT_PLAYER, "SELECT PLAYER"},
        {Conditions::Type::LOSE_WEAPONS, "LOSE WEAPONS"},
        {Conditions::Type::LOSE_ARMOUR, "LOSE ARMOUR"},
        {Conditions::Type::ITEM_EFFECT, "ITEM EFFECT"},
        {Conditions::Type::STAKE, "STAKE"},
        {Conditions::Type::GET, "GET"},
        {Conditions::Type::SET, "SET"},
        {Conditions::Type::NUMBER, "NUMBER"},
        {Conditions::Type::COPY, "COPY"},
        {Conditions::Type::MATH, "MATH"},
        {Conditions::Type::ROLL, "ROLL"},
        {Conditions::Type::IF, "IF"},
        {Conditions::Type::IF_MATH, "IF MATH"},
        {Conditions::Type::AND, "AND"},
        {Conditions::Type::OR, "OR"},
        {Conditions::Type::ADD_TO_ITEM, "ADD TO ITEM"},
        {Conditions::Type::SHOW_VARIABLES, "SHOW VARIABLES"},
        {Conditions::Type::EAT_FOOD, "EAT FOOD"},
        {Conditions::Type::SHOW_MESSAGE, "SHOW MESSAGE"},
        {Conditions::Type::TEXTBOX, "TEXTBOX"},
        {Conditions::Type::COUNT_ITEMS, "COUNT ITEMS"},
        {Conditions::Type::PSYCHIC_SPELL, "PSYCHIC SPELL"},
        {Conditions::Type::IS_DEAD, "IS DEAD"},
        {Conditions::Type::COLLECT, "COLLECT"},
        {Conditions::Type::PERMANENT_ATTRIBUTE_GAIN, "PERMANENT ATTRIBUTE GAIN"},
        {Conditions::Type::CHARGE, "CHARGE"},
        {Conditions::Type::DISCHARGE, "DISCHARGE"},
        {Conditions::Type::KILL_PLAYER, "KILL PLAYER"},
        {Conditions::Type::GAIN_ATTRIBUTE, "GAIN ATTRIBUTE"},
        {Conditions::Type::REVEAL_ITEM, "REVEAL ITEM"},
        {Conditions::Type::DAMAGE_PLAYER, "DAMAGE PLAYER"},
        {Conditions::Type::FAIL_THEN_DIE, "FAIL THEN DIE"},
        {Conditions::Type::SELECT_DICE, "SELECT DICE"},
        {Conditions::Type::MULTIPLE_DICE, "MULTIPLE DICE"}};

    Conditions::Type Map(const char *Conditions)
    {
        return BloodSword::Find(Conditions::TypeMapping, Conditions);
    }

    Conditions::Type Map(std::string Conditions)
    {
        return Conditions::Map(Conditions.c_str());
    }
}

#endif
