#ifndef __CONDITION_TYPES_HPP__
#define __CONDITION_TYPES_HPP__

#include "Templates.hpp"

namespace BloodSword::Conditions
{
    enum class Type
    {
        NONE = -1,
        NORMAL,
        IN_PARTY,
        CHOOSE_PLAYER,
        CHOSEN_PLAYER,
        BATTLE_VICTORY,
        BATTLE_FLEE,
        BATTLE_ENTHRALMENT,
        BATTLE_VICTORY_OR_ENTHRALMENT,
        PARTY_HAS_ITEM,
        HAS_CHARGED_ITEM,
        USE_ITEM,
        USE_ITEMS,
        DROP_ITEM,
        TAKE_ITEM,
        GET_ITEM,
        HAS_ITEM,
        REVEAL_ITEM,
        TAKE_ITEMS,
        GAIN_ENDURANCE,
        LOSE_ENDURANCE,
        CHOOSE_NUMBER,
        CHOSEN_NUMBER,
        PARTY_WOUNDED,
        PREVIOUS_LOCATION,
        TEST_ATTRIBUTE,
        LOSE_ALL,
        HAVE_COLLEAGUES,
        SOLO,
        GAIN_STATUS,
        LOSE_STATUS,
        FIRST,
        LAST,
        TEST_GAIN_STATUS,
        COUNT_STATUS,
        SELECT_MULTIPLE,
        CALL_TO_MIND,
        FORGET_SPELL,
        KALUGEN_SELECT,
        KALUGEN_SCORE,
        KALUGEN_LIST,
        KALUGEN_PLAY,
        DISCARD_ITEMS,
        RECEIVE_ITEM,
        IN_PARTY_WITH_ITEM,
        SELECT_PLAYER,
        SET_CHOSEN,
        LOSE_WEAPONS,
        LOSE_ARMOUR,
        LOSE_UNEQUIPPED,
        ITEM_EFFECT,
        STAKE,
        SET,
        GET,
        NUMBER,
        COPY,
        MATH,
        ROLL,
        IF,
        IF_MATH,
        AND,
        OR,
        ADD_TO_ITEM,
        SHOW_VARIABLES,
        EAT_FOOD,
        SHOW_MESSAGE,
        TEXTBOX,
        HAS_QUANTITY_OF_ITEM,
        PSYCHIC_SPELL,
        PSYCHIC_SPELL_GAIN_ATTRIBUTE,
        IS_DEAD,
        COLLECT,
        PERMANENT_ATTRIBUTE_GAIN,
        CHARGE,
        DISCHARGE,
        KILL_PLAYER,
        REMOVE_PLAYER,
        GAIN_ATTRIBUTE,
        DAMAGE_PLAYER,
        FAIL_THEN_DIE,
        SELECT_DICE,
        MULTIPLE_DICE,
        IS_ALIVE,
        IF_TRUE_SET,
        IF_FALSE_SET,
        IF_TRUE_RETURN,
        IF_FALSE_RETURN,
        COMPUTE_VICTORY_POINTS,
        GAIN_EXPERIENCE,
        TEST_DISCHARGE_ITEM,
        TASK,
        CONFIRM,
        LOSE_EVERYTHING,
        LOSE_EVERYTHING_EXCEPT_WEAPONS,
        TAKE_FROM_LIST,
        GAUNTLET,
        ORDER_FRONT,
        ORDER_FIRST,
        ORDER_BACK,
        ORDER_LAST,
        DAMAGE_ON_FAIL,
        DAMAGE_PARTY_ON_FAIL,
        ITEM_IN_ENVIRONMENT,
        ITEM_IN_SECTION,
        ADD_CHARACTER,
        COMBAT_TASK,
        COMBAT_MISSION,
        HAS_ALL_ITEMS,
        DAMAGE_PARTY,
        GAIN_ARMOUR,
        LOSE_ENDURANCE_OR_DROP_ITEM,
        PLAYER_PAYS,
        CHARACTER_PAYS,
        MAXIMISE_ATTRIBUTE,
        MAXIMIZE_ATTRIBUTE,
        MODIFY_ATTRIBUTE,
        RANDOM_OUTCOME,
        KILL_ALL_WITH_STATUS,
        ALL_WITH_STATUS_GAIN_ATTRIBUTE,
        ALL_WITH_STATUS_MODIFY_ATTRIBUTE,
        PLAYER_BUYS_ITEM,
        CHARACTER_BUYS_ITEM,
        CHAOS_EFFECT,
        COUNT_ITEMS,
        IS_WOUNDED,
        MUST_GET_ITEM,
        MUST_TAKE_ITEM
    };

    BloodSword::Mapping<Conditions::Type> TypeMapping = {
        {Conditions::Type::NONE, "NONE"},
        {Conditions::Type::NORMAL, "NORMAL"},
        {Conditions::Type::IN_PARTY, "IN PARTY"},
        {Conditions::Type::CHOOSE_PLAYER, "CHOOSE PLAYER"},
        {Conditions::Type::CHOSEN_PLAYER, "CHOSEN PLAYER"},
        {Conditions::Type::BATTLE_VICTORY, "BATTLE VICTORY"},
        {Conditions::Type::BATTLE_FLEE, "BATTLE FLEE"},
        {Conditions::Type::BATTLE_ENTHRALMENT, "BATTLE ENTHRALMENT"},
        {Conditions::Type::BATTLE_VICTORY_OR_ENTHRALMENT, "BATTLE VICTORY OR ENTHRALMENT"},
        {Conditions::Type::PARTY_HAS_ITEM, "PARTY HAS ITEM"},
        {Conditions::Type::HAS_CHARGED_ITEM, "HAS CHARGED ITEM"},
        {Conditions::Type::USE_ITEM, "USE ITEM"},
        {Conditions::Type::USE_ITEMS, "USE ITEMS"},
        {Conditions::Type::DROP_ITEM, "DROP ITEM"},
        {Conditions::Type::TAKE_ITEM, "TAKE ITEM"},
        {Conditions::Type::GET_ITEM, "GET ITEM"},
        {Conditions::Type::HAS_ITEM, "HAS ITEM"},
        {Conditions::Type::TAKE_ITEMS, "TAKE ITEMS"},
        {Conditions::Type::GAIN_ENDURANCE, "GAIN ENDURANCE"},
        {Conditions::Type::LOSE_ENDURANCE, "LOSE ENDURANCE"},
        {Conditions::Type::CHOOSE_NUMBER, "CHOOSE NUMBER"},
        {Conditions::Type::CHOSEN_NUMBER, "CHOSEN NUMBER"},
        {Conditions::Type::PARTY_WOUNDED, "PARTY WOUNDED"},
        {Conditions::Type::PREVIOUS_LOCATION, "PREVIOUS LOCATION"},
        {Conditions::Type::TEST_ATTRIBUTE, "TEST ATTRIBUTE"},
        {Conditions::Type::LOSE_ALL, "LOSE ALL"},
        {Conditions::Type::HAVE_COLLEAGUES, "HAVE COLLEAGUES"},
        {Conditions::Type::SOLO, "SOLO"},
        {Conditions::Type::GAIN_STATUS, "GAIN STATUS"},
        {Conditions::Type::FIRST, "FIRST"},
        {Conditions::Type::LAST, "LAST"},
        {Conditions::Type::TEST_GAIN_STATUS, "TEST GAIN STATUS"},
        {Conditions::Type::COUNT_STATUS, "COUNT STATUS"},
        {Conditions::Type::LOSE_STATUS, "LOSE STATUS"},
        {Conditions::Type::SELECT_MULTIPLE, "SELECT MULTIPLE"},
        {Conditions::Type::CALL_TO_MIND, "CALL TO MIND"},
        {Conditions::Type::FORGET_SPELL, "FORGET SPELL"},
        {Conditions::Type::KALUGEN_SELECT, "KALUGEN SELECT"},
        {Conditions::Type::KALUGEN_SCORE, "KALUGEN SCORE"},
        {Conditions::Type::KALUGEN_LIST, "KALUGEN LIST"},
        {Conditions::Type::KALUGEN_PLAY, "KALUGEN PLAY"},
        {Conditions::Type::DISCARD_ITEMS, "DISCARD ITEMS"},
        {Conditions::Type::RECEIVE_ITEM, "RECEIVE ITEM"},
        {Conditions::Type::IN_PARTY_WITH_ITEM, "IN PARTY WITH ITEM"},
        {Conditions::Type::SELECT_PLAYER, "SELECT PLAYER"},
        {Conditions::Type::SET_CHOSEN, "SET CHOSEN"},
        {Conditions::Type::LOSE_WEAPONS, "LOSE WEAPONS"},
        {Conditions::Type::LOSE_ARMOUR, "LOSE ARMOUR"},
        {Conditions::Type::LOSE_UNEQUIPPED, "LOSE UNEQUIPPED"},
        {Conditions::Type::ITEM_EFFECT, "ITEM EFFECT"},
        {Conditions::Type::STAKE, "STAKE"},
        {Conditions::Type::GET, "GET"},
        {Conditions::Type::SET, "SET"},
        {Conditions::Type::NUMBER, "NUMBER"},
        {Conditions::Type::COPY, "COPY"},
        {Conditions::Type::MATH, "MATH"},
        {Conditions::Type::ROLL, "ROLL"},
        {Conditions::Type::IF, "IF"},
        {Conditions::Type::IF_MATH, "IF MATH"},
        {Conditions::Type::AND, "AND"},
        {Conditions::Type::OR, "OR"},
        {Conditions::Type::ADD_TO_ITEM, "ADD TO ITEM"},
        {Conditions::Type::SHOW_VARIABLES, "SHOW VARIABLES"},
        {Conditions::Type::EAT_FOOD, "EAT FOOD"},
        {Conditions::Type::SHOW_MESSAGE, "SHOW MESSAGE"},
        {Conditions::Type::TEXTBOX, "TEXTBOX"},
        {Conditions::Type::HAS_QUANTITY_OF_ITEM, "HAS QUANTITY OF ITEM"},
        {Conditions::Type::PSYCHIC_SPELL, "PSYCHIC SPELL"},
        {Conditions::Type::PSYCHIC_SPELL_GAIN_ATTRIBUTE, "PSYCHIC SPELL GAIN ATTRIBUTE"},
        {Conditions::Type::IS_DEAD, "IS DEAD"},
        {Conditions::Type::COLLECT, "COLLECT"},
        {Conditions::Type::PERMANENT_ATTRIBUTE_GAIN, "PERMANENT ATTRIBUTE GAIN"},
        {Conditions::Type::CHARGE, "CHARGE"},
        {Conditions::Type::DISCHARGE, "DISCHARGE"},
        {Conditions::Type::KILL_PLAYER, "KILL PLAYER"},
        {Conditions::Type::REMOVE_PLAYER, "REMOVE PLAYER"},
        {Conditions::Type::GAIN_ATTRIBUTE, "GAIN ATTRIBUTE"},
        {Conditions::Type::REVEAL_ITEM, "REVEAL ITEM"},
        {Conditions::Type::DAMAGE_PLAYER, "DAMAGE PLAYER"},
        {Conditions::Type::FAIL_THEN_DIE, "FAIL THEN DIE"},
        {Conditions::Type::SELECT_DICE, "SELECT DICE"},
        {Conditions::Type::MULTIPLE_DICE, "MULTIPLE DICE"},
        {Conditions::Type::IS_ALIVE, "IS ALIVE"},
        {Conditions::Type::IF_TRUE_SET, "IF TRUE SET"},
        {Conditions::Type::IF_FALSE_SET, "IF FALSE SET"},
        {Conditions::Type::GAIN_EXPERIENCE, "GAIN EXPERIENCE"},
        {Conditions::Type::COMPUTE_VICTORY_POINTS, "COMPUTE VICTORY POINTS"},
        {Conditions::Type::TEST_DISCHARGE_ITEM, "TEST DISCHARGE ITEM"},
        {Conditions::Type::TASK, "TASK"},
        {Conditions::Type::CONFIRM, "CONFIRM"},
        {Conditions::Type::LOSE_EVERYTHING, "LOSE EVERYTHING"},
        {Conditions::Type::LOSE_EVERYTHING_EXCEPT_WEAPONS, "LOSE EVERYTHING EXCEPT WEAPONS"},
        {Conditions::Type::TAKE_FROM_LIST, "TAKE FROM LIST"},
        {Conditions::Type::GAUNTLET, "GAUNTLET"},
        {Conditions::Type::ORDER_FRONT, "ORDER FRONT"},
        {Conditions::Type::ORDER_FIRST, "ORDER FIRST"},
        {Conditions::Type::ORDER_BACK, "ORDER BACK"},
        {Conditions::Type::ORDER_LAST, "ORDER LAST"},
        {Conditions::Type::IF_TRUE_RETURN, "IF TRUE RETURN"},
        {Conditions::Type::IF_FALSE_RETURN, "IF FALSE RETURN"},
        {Conditions::Type::DAMAGE_ON_FAIL, "DAMAGE ON FAIL"},
        {Conditions::Type::DAMAGE_PARTY_ON_FAIL, "DAMAGE PARTY ON FAIL"},
        {Conditions::Type::ITEM_IN_ENVIRONMENT, "ITEM IN ENVIRONMENT"},
        {Conditions::Type::ITEM_IN_SECTION, "ITEM IN SECTION"},
        {Conditions::Type::ADD_CHARACTER, "ADD CHARACTER"},
        {Conditions::Type::COMBAT_TASK, "COMBAT TASK"},
        {Conditions::Type::COMBAT_MISSION, "COMBAT MISSION"},
        {Conditions::Type::HAS_ALL_ITEMS, "HAS ALL ITEMS"},
        {Conditions::Type::DAMAGE_PARTY, "DAMAGE PARTY"},
        {Conditions::Type::GAIN_ARMOUR, "GAIN ARMOUR"},
        {Conditions::Type::LOSE_ENDURANCE_OR_DROP_ITEM, "LOSE ENDURANCE OR DROP ITEM"},
        {Conditions::Type::PLAYER_PAYS, "PLAYER PAYS"},
        {Conditions::Type::CHARACTER_PAYS, "CHARACTER PAYS"},
        {Conditions::Type::MAXIMISE_ATTRIBUTE, "MAXIMISE ATTRIBUTE"},
        {Conditions::Type::MAXIMIZE_ATTRIBUTE, "MAXIMIZE ATTRIBUTE"},
        {Conditions::Type::MODIFY_ATTRIBUTE, "MODIFY ATTRIBUTE"},
        {Conditions::Type::RANDOM_OUTCOME, "RANDOM OUTCOME"},
        {Conditions::Type::KILL_ALL_WITH_STATUS, "KILL ALL WITH STATUS"},
        {Conditions::Type::ALL_WITH_STATUS_GAIN_ATTRIBUTE, "ALL WITH STATUS GAIN ATTRIBUTE"},
        {Conditions::Type::ALL_WITH_STATUS_MODIFY_ATTRIBUTE, "ALL WITH STATUS MODIFY ATTRIBUTE"},
        {Conditions::Type::PLAYER_BUYS_ITEM, "PLAYER BUYS ITEM"},
        {Conditions::Type::CHARACTER_BUYS_ITEM, "CHARACTER BUYS ITEM"},
        {Conditions::Type::COUNT_ITEMS, "COUNT ITEMS"},
        {Conditions::Type::CHAOS_EFFECT, "CHAOS EFFECT"},
        {Conditions::Type::IS_WOUNDED, "IS WOUNDED"},
        {Conditions::Type::MUST_GET_ITEM, "MUST GET ITEM"},
        {Conditions::Type::MUST_TAKE_ITEM, "MUST TAKE ITEM"}};

    Conditions::Type Map(const char *Conditions)
    {
        return BloodSword::Find(Conditions::TypeMapping, Conditions);
    }

    Conditions::Type Map(std::string Conditions)
    {
        return Conditions::Map(Conditions.c_str());
    }
}

#endif
