#ifndef __CONTROL_TYPES_HPP__
#define __CONTROL_TYPES_HPP__

#include <vector>

namespace BloodSword::Controls
{
    enum class Type
    {
        NONE = -1,
        ANY = 0,
        WARRIOR,
        TRICKSTER,
        SAGE,
        ENCHANTER,
        SCROLL_UP,
        SCROLL_DOWN,
        MAP_NONE,
        MAP_UP,
        MAP_DOWN,
        MAP_LEFT,
        MAP_RIGHT,
        MAP_EXIT,
        BACK,
        RESET,
        CONFIRM,
        ROLL,
        PLAYER,
        ENEMY,
        DESTINATION,
        ABILITY,
        ITEMS,
        CALL_TO_MIND,
        FORGET,
        FLEE,
        MOVE,
        HEAL,
        PLUS,
        MINUS,
        ATTACK,
        DEFEND,
        SHOOT,
        CAST,
        DAMAGE,
        ARCHERY,
        DODGING,
        QUARTERSTAFF,
        EXORCISM,
        ESP,
        PARANORMAL_SIGHT,
        LEVITATION,
        SPELLS,
        TEST,
        CHOICE,
        CONTINUE,
        MAP,
        ENCYCLOPEDIA,
        NEW,
        LOAD,
        SAVE,
        EXIT,
        GAME,
        PARTY,
        INFO,
        USE,
        DROP,
        TRANSFER,
        TAKE,
        TEMPORARY_OBSTACLE,
        VOLCANO_SPRAY,
        NIGHTHOWL,
        WHITE_FIRE,
        SWORDTHRUST,
        EYE_OF_THE_TIGER,
        IMMEDIATE_DELIVERANCE,
        MISTS_OF_DEATH,
        THE_VAMPIRE_SPELL,
        PILLAR_OF_SALT,
        SHEET_LIGHTNING,
        GHASTLY_TOUCH,
        NEMESIS_BOLT,
        SERVILE_ENTHRALMENT,
        SUMMON_FALTYN,
        PREDICTION,
        DETECT_ENCHANTMENT
    };

    std::vector<Controls::Type> Spells = {
        Type::VOLCANO_SPRAY,
        Type::NIGHTHOWL,
        Type::WHITE_FIRE,
        Type::SWORDTHRUST,
        Type::EYE_OF_THE_TIGER,
        Type::IMMEDIATE_DELIVERANCE,
        Type::MISTS_OF_DEATH,
        Type::THE_VAMPIRE_SPELL,
        Type::PILLAR_OF_SALT,
        Type::SHEET_LIGHTNING,
        Type::GHASTLY_TOUCH,
        Type::NEMESIS_BOLT,
        Type::SERVILE_ENTHRALMENT,
        Type::SUMMON_FALTYN,
        Type::PREDICTION,
        Type::DETECT_ENCHANTMENT
    };
}
#endif
